### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by KanzaTahreem** [KanzaTahreem/Portfolio-Website#13]
Leave your feedback here.💡

**Comment by carreraprogrammer** [comment]
You are doing an excellent job!

Your project has all the requirements and looks beautiful, keep it up!  🥳

**Comment by MahdiAghaali** [comment]
This is an example of a perfect job,
the only thing that I can think of is that you can break down your javascript and CSS files into smaller files and give them meaningful names so you can reuse them in the future, also helps with the management of your code, you can easily find the module you're looking for without scrolling 2000 lines of code if you have them all in the same file.
![dasdsadasdas](https://user-images.githubusercontent.com/93377744/189151116-f6ae08ae-b2be-4104-b058-3e2dab85d400.JPG)
